### ISSUE TITLE
"Not for production use" is not discoverable

### ISSUE THREAD

**Issue by gbiellem** [Particular/PlatformInstaller#157]
The docs site has a disclaimer (see below) regarding the PI, but the download page and the platform installer application do not mention that it is for development machines.  

```
NOTE: The platform Installer is recommended for use in development environments. 
For testing and production environments it is recommended you use the relevant Chocolatey commands, PowerShell cmdlets and NuGet packages
```

What should we do about this?

//cc @SimonCropp @dannycohen @andreasohlund

**Comment by SimonCropp** [comment]
changed the selection screen to look like this 
![sdk](https://cloud.githubusercontent.com/assets/122666/7447871/ae52808a-f24d-11e4-9187-3fa8257cf32f.png)
