### ISSUE TITLE
Remove Perf Counters package from PI

### ISSUE THREAD

**Issue by gbiellem** [Particular/PlatformInstaller#161]
In   https://github.com/Particular/NServiceBus.Host/issues/26  the plan in to make Performances Counter opt-in.  In this case it would also make sense not to install them by default.

**Comment by gbiellem** [comment]
Related to https://github.com/Particular/ServiceControl/issues/418.

**Comment by gbiellem** [comment]
Also related to this https://github.com/Particular/ServiceControlInstaller/issues/1#issuecomment-72603079

**Comment by gbiellem** [comment]
We'll do this in conjunction with release of ServiceControl Installer. Park it for now.

**Comment by SimonCropp** [comment]
@andreasohlund what about people still using older versions of NSB? they still need perf counters.

**Comment by andreasohlund** [comment]
They can install them using the powershell scripts provided by @gbiellem ?

**Comment by SimonCropp** [comment]
ok. @gbiellem u want to do this? or u want me to?

**Comment by gbiellem** [comment]
Rather than a blanket removal. Let's make it optional ( Same as MSMQ - #178 )

**Comment by gbiellem** [comment]
Closing in favor of #181
