### ISSUE TITLE
PI Check for VS Express editions fails 

### ISSUE THREAD

**Issue by gbiellem** [Particular/PlatformInstaller#163]
See desk case 8060

The user has a full version of VS2013 and an expresss version of VS2012.   PI ran both ServiceMatrix 2012 and 2013  packages instead of only running the SM 2013 package. 

In this instance there was a VSIXInstaller.exe  at in the %VS110COMNTOOLS%\IDE  directory so it seems the logic [here] (https://github.com/Particular/PlatformInstaller/blob/master/src/PlatformInstaller/VisualStudioDetecter.cs#L57)    is based on a false premise

**Comment by distantcam** [comment]
@gbiellem Is this a PI issue or a SM problem?

**Comment by gbiellem** [comment]
I think this is a PI issue.  It's only looking for the presence of VSIXInstaller.exe prior to attempting an install.  It should be checking that the VS is a supported edition as well

**Comment by gbiellem** [comment]
We now show expose the VSIXInstaller log file location as part of the error.  The log  clearly states that the a supported version is not found. I've also updated the tooltip on the SM option to state that the VS Professional or higher is required.  This should be enough for this edge case
