### ISSUE TITLE
Install .Net 4.5.2 as a pre-requisite for V6

### ISSUE THREAD

**Issue by gbiellem** [Particular/PlatformInstaller#179]
Update PI to ensure .Net 4.5.2. is installed for V6 

### Plan of Attack - Last Update 03 March 2016
1.  Update ClickOnce Bootstrapper to deploy  4.5.2 as a prerequisite. (This targets fresh installs)
 - [x]  PI Test Version
 - [x]  PI Prod Version

1. Update ClickOnce Deployment Scripts to install 4.5.2 as a prerequisite.  (This targets users who upgrade via clickonce)
 - [x]  Add check for to see it 4.5.2 or greater is installed. 
 - [x] Add download and install logic
 - [x] Adjust UI 
 - [x] Test 
 - [x] Deploy

The  plan is to deploy this as soon as it's ready as there is no dependency on V6 being ready.

**Comment by gbiellem** [comment]
@johnsimons  & @SimonCropp 

I looked into this after our zoom chat.

Updating the manifest file for the click-once bootstrapper setup.exe would address new installs.
This doesn't work for upgrades though as the auto-update only pulls down the new PI binaries - it doesn't run the bootstrapper again.

So at this stage I don't have a nice way of doing it using the out of the box click once tools. 

I for common workarounds and all I came up with was an approach that requires V2 of the package  on a new URL and change the V1 to autorun the bootstrapper for V2.  Not sure how ugly that will be in practice.

**Comment by SimonCropp** [comment]
can we handle it inside the PI UI? update the manifest for all new users and detect it for old users the next time they run and prompt them?

**Comment by gbiellem** [comment]
Yes @SimonCropp I think we'll have to do somehting like that

**Comment by gbiellem** [comment]
@SimonCropp  should we consider splitting out NSB prerequisites into discrete options as part of this work and make them unticked by default.
  
The are not really prerequisites any more for the platform, so they should be options.

**Comment by SimonCropp** [comment]
@gbiellem i think we should. but i would prefer to do in another release??

**Comment by gbiellem** [comment]
Sold. Ill raise a ne issue for that

**Comment by gbiellem** [comment]
This has now been tested and is deployed.
@SimonCropp  please merge associated docs.
