### ISSUE TITLE
Distinct name for installer executable

### ISSUE THREAD

**Issue by adamralph** [Particular/PlatformInstaller#189]
Currently, the name is "setup.exe". It would better if it had a distinct name a) to be recognisable after the initial download and b) to avoid a conflict with another installer which might choose that name.

Perhaps "ParticularPlatform.exe"?

Is it worth adding the version number too?

/cc @Particular/platforminstaller-maintainers

**Comment by gbiellem** [comment]
> Is it worth adding the version number too?

I don't think so.   The setup.exe is  a click once bootstrapper to pull down the real PI exe from a URL.  It's not linked to a specific version and when run will always pull the latest.  So having a version number on the bootstrapper would be misleading.

**Comment by gbiellem** [comment]
Deployment scripts and readme.md  updated. 

Currently both Setup.exe and ParticularPlatform.exe are being deployed.  I plan to leave this open until the related change in the front end is done and then we can update the deployment to remove the Setup.exe.

**Comment by adamralph** [comment]
@gbiellem out of interest, I can't see any commits related to this. Is this is purely TC config?

**Comment by gbiellem** [comment]
Correct - the generation of bootstrapper is all in TC

**Comment by gbiellem** [comment]
All done
