### ISSUE TITLE
Update license agreement 

### ISSUE THREAD

**Issue by indualagarsamy** [Particular/PlatformInstaller#193]
As part of https://github.com/Particular/OptimizeTrialExtensions/issues/114, we are working to change the license agreement and privacy policy to be compliant. 

Once we have the right text, the Platform Installer will need to reflect that.

cc / @kbaley

**Comment by YifatS** [comment]
Link to the [approved evaluation license agreement]( https://docs.google.com/document/d/1TaTMDIHHuYgCT1g4BXjeNp5GOjLA6S2nctehri_Q4Xo/edit#).
@indualagarsamy @kbaley

**Comment by indualagarsamy** [comment]
The correct link to the evaluation license agreement is here:
https://docs.google.com/document/d/1ulv4Q0jIe8CZZt3p97Y_jLFEFWigL5dtWd3fLCXRqAw/edit#
