### ISSUE TITLE
Installation of ServiceControl failed with exitcode: -536870911

### ISSUE THREAD

**Issue by udidahan** [Particular/PlatformInstaller#197]
[log-20170309.txt](https://github.com/Particular/PlatformInstaller/files/830755/log-20170309.txt)

**Comment by gbiellem** [comment]
@udidahan  I've found the issue thanks to your log file. 
The cause of the failure is the command line passed to the downloaded installers was not quoting the MSI log file path if it contained spaces. Which is also why it didn't get created in #198

**Comment by gbiellem** [comment]
Change has been deployed
