### ISSUE TITLE
Incorrect log file name when platform installer fails.

### ISSUE THREAD

**Issue by udidahan** [Particular/PlatformInstaller#198]
When the platform installer failed as I described in issue #197, the message that was shown to me was:

> Installation of ServiceControl failed with exitcode: -536870911
> The MSI installation log can be found at C:\Users\Udi Dahan\AppData\Roaming\PlatformInstaller\particular.servicecontrol.installer.log

Now, there is no file called "particular.servicecontrol.installer.log" in my PlatformInstaller directory, but there is a file called "log-20170309.txt".

It would have been better had the error message in the platform installer told me the correct name of the file.

**Comment by gbiellem** [comment]
Closing this.  The message is actually correct. The file was not created due to a bug as outlined in #197
