### ISSUE TITLE
When Core deprecates performance counters remove performance counter installation script

### ISSUE THREAD

**Issue by danielmarbach** [Particular/PlatformInstaller#207]

**Comment by danielmarbach** [comment]
@Particular/nservicebus-maintainers I couldn't find another issue in the core repo to cross link this. With the new performance counter package msbuild task the package is self-contained and can generate the installation scripts automatically as build artifacts. So when the core removes the perf counters the platform installer can be updated as well.

**Comment by danielmarbach** [comment]
Another option would be to reference NServiceBus Performance counters, use the msbuild task and ship the dynamic script with the installer.

**Comment by SzymonPobiega** [comment]
I'd say 
 * remove the script from PI
 * update the doco

should be enough

**Comment by danielmarbach** [comment]
Thoughts on the above @Particular/platforminstaller-maintainers ?

**Comment by timbussmann** [comment]
👍 for @SzymonPobiega proposal.

**Comment by gbiellem** [comment]
👍.  for @SzymonPobiega  proposal from me too

**Comment by WojcikMike** [comment]
I created 2 PR's to implement @SzymonPobiega wishes. Please review

**Comment by gbiellem** [comment]
I had some time in an airport lounge,  The PI change is merged and I've smoke tested the staged version.  When you are ready to go just promote this deploy to prod  in [Octopus](https://deploy.particular.net/app#/projects/PlatformInstaller/releases/1.0.0.584)..

**Comment by danielmarbach** [comment]
Fixed as part of #212
