### ISSUE TITLE
ServicePulse version mismatch between website (1.10.1) and platform installer (1.9.1)

### ISSUE THREAD

**Issue by ramonsmits** [Particular/PlatformInstaller#219]
The download page currently shows ServicePulse version 1.10.1 but the platform installer currently shows ServicePulse version 1.9.1

![image](https://user-images.githubusercontent.com/152998/33341270-b73a29c6-d47e-11e7-9bce-8159576dac90.png)

![image](https://user-images.githubusercontent.com/152998/33341274-ba822868-d47e-11e7-86a8-0c424eb95afd.png)

**Comment by WilliamBZA** [comment]
This is because the beta release was promoted manually in GitHub instead of using the release process in Octopus. This will be resolved once the next release is done.

**Comment by tmasternak** [comment]
Verfied with @ramonsmits . It's ok.
