### ISSUE TITLE
Install RabbitMQ

### ISSUE THREAD

**Issue by andreasohlund** [Particular/PlatformInstaller#25]
If the user selects RabbitMQ as transport we should install it for them.

Package:

http://chocolatey.org/packages/rabbitmq

**Comment by SimonCropp** [comment]
@andreasohlund this will need design changes to the UI to capture the transport. can u please move this to requirements

**Comment by andreasohlund** [comment]
Talked this through with @gbiellem and this will be tracked as part of doing the new SC installer.

Closing this one
