### ISSUE TITLE
Create start menu items

### ISSUE THREAD

**Issue by andreasohlund** [Particular/PlatformInstaller#48]
Under "Particular Service Platform"
- [ ] Link to Samples landing page -http://docs.particular.net/platform/samples/
- [ ] Link to release notes landing page  - [http://particular.net/releasenotes](https://github.com/Particular/Website.Frontend/issues/99)

**Comment by SimonCropp** [comment]
this is no longer relevant. we went a singe repo approach for samples. they are all located here http://docs.particular.net/platform/samples/ with associated zip downloads
