### ISSUE TITLE
In Progress Details, highlight failures text

### ISSUE THREAD

**Issue by dannycohen** [Particular/PlatformInstaller#67]
In the progress details it takes a bit of effort to notice the problems, since they are not highlighted in any way (See below).

I would be best if they can be highlighted (red font color ?)

![image](https://f.cloud.github.com/assets/3889023/2515653/861e177e-b445-11e3-9790-74427ddf4983.png)

**Comment by adamralph** [comment]
:+1: 

The latest choco (0.9.8.33) shows a red warning message when installing (the part beginning with `!!ATTENTION!!`, but in the platform installer (downloaded today - I'm not sure which version it is) things are still in b/w.

![image](https://cloud.githubusercontent.com/assets/677704/6314294/385a369a-b9d9-11e4-81c8-2a7faa21fc14.png)
