### ISSUE TITLE
"Update" is not an update

### ISSUE THREAD

**Issue by johnsimons** [Particular/PlatformInstaller#86]
![image](https://cloud.githubusercontent.com/assets/122651/2574664/f30c656a-b937-11e3-9a79-2e367bba3b10.png)

Currently PI reports an update if the chocolatey package has previously been d/l.
This is confusing, as a user I was expecting a "product update" not a reinstall of the current version.

**Comment by gbiellem** [comment]
Addressed as part of removal of chocolatey
